In [56]:
import numpy as np

In [57]:
# convert python list to numpy array and use its method.
l=[i*10 for i in range(10)]
np_array = np.array(l)
print(np_array.shape)
print(np_array.ndim)
print(np_array.dtype)
print(np_array.size)

(10,)
1
int32
10


In [58]:
#creating a random array values
from numpy.random import default_rng
rng = default_rng(12345)
print(rng.random(10))
mean,stddev=5,1
print(rng.normal(mean,stddev,size=10))

[0.22733602 0.31675834 0.79736546 0.67625467 0.39110955 0.33281393
 0.59830875 0.18673419 0.67275604 0.94180287]
[7.34740965 5.96849691 4.24061282 5.90219827 4.53304683 4.93931048
 5.78884434 3.74333187 5.57585751 6.39897899]


In [67]:
#create array using numpy of 5 rowa nd 2 columns.
#create random ra with (3,3) shape
import numpy as np
from numpy.random import default_rng
np_array1=np.linspace(10,100,10).reshape(5,2)
print(np_array1)
#or
np_array2=np.arange(10,101,10).reshape(5,2)
print(np_array2)
rng_array= default_rng()
random_array=rng_array.random(9).reshape(3,3)
print(random_array)



[[ 10.  20.]
 [ 30.  40.]
 [ 50.  60.]
 [ 70.  80.]
 [ 90. 100.]]
[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]
[[0.60839931 0.3624512  0.83917698]
 [0.9818088  0.88220989 0.62168415]
 [0.54135022 0.72309846 0.30217268]]


In [100]:
#print first 2 rows
#print first column
#print 2nd element of 3rd row
import numpy as np
np_arr=np.arange(9).reshape(3,3)
print(np_arr)
#arr[row,column]
#print(np_arr[:2,:3])
print(np_arr[:,0])
print(np_arr[2,1])



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 3 6]
7


In [118]:
# add 5 to to all customer data amount
import numpy as np
cust_data = np.array([5.99,4.99,6.7,7])
print(cust_data+5)
d=cust_data-1
print((d*cust_data).sum())


[10.99  9.99 11.7  12.  ]
129.99020000000002


6


In [4]:
#filtering(using operators and where)
#filter product list to only incluse price >25
import numpy as np
product=np.array(["tomato","cola","icecream","cake"])
price= np.array([10,150,50,100])
print(product[(price>25)])

mask =(price > 25) | (product == "cola")
print(product[mask])

shipping_cost=np.where(price>20,0,5)
print(shipping_cost)

[5 0 0 0]


In [30]:
#agregate Funcions(sum,min,max,mean),Array Functions(median,percentile,unique,sqrt),
#sort method
import numpy as np
price=np.arange(1,15)
minimum_price = min(price)
print(minimum_price)
maximum_price=max(price)
print(maximum_price)
median_price = np.median(price)
print(median_price)
sort_array=np.sort(price)
print(sort_array)
print(np.unique(price))

1
14
7.5
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
## vectorization and broadcasting
#vectorization-is the process of pushing array operations into optimized c code, which is easier and more efficient than writing for loops
#broadcasting-lets u perform vectorized operations with arrays of different sizes. where numpy will expand the smaller array to 'fit' the larger one
#numpy arrays are semi-mutable and we can modify values but we cant modify its size